spring:
  application:
    name: catalyst
  datasource:
    url: jdbc:postgresql://localhost:5432/catalystdb
    username: catalyst
    password: medaware
    driver-class-name: org.postgresql.Driver
server:
  port: 8080
springdoc:
  swagger-ui:
    url: /catalyst-api-docs