spring:
  application:
    name: catalyst
  datasource:
    url: jdbc:postgresql://localhost:5432/catalystdb
    username: catalyst
    password: medaware
    driver-class-name: org.postgresql.Driver
  flyway:
    create-schemas: true
    schemas:
      - catalyst
server:
  port: 8080
springdoc:
  swagger-ui:
    url: /catalyst-api-docs

catalyst:
  default-access:
    username: admin
    password: admin