spring:
  application:
    name: catalyst
  datasource:
    url: jdbc:postgresql://mawd-postgres:5432/catalystdb
    username: catalyst
    password: medaware
    driver-class-name: org.postgresql.Driver
  flyway:
    create-schemas: true
    schemas:
      - catalyst
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB

server:
  port: 8080
  address: 0.0.0.0
springdoc:
  swagger-ui:
    url: /catalyst-api-docs

catalyst:
  server: https://api.medaware.dev
  default-access:
    username: admin
    password: admin
  minio:
    endpoint: http://mawd-minio:9000
    access-key: catalyst
    secret-key: medaware
    bucket: catalyst-resources
  default-topic:
    name: Fallback
    description: The default fallback topic
    color: "#bdc3c7"
  ocr:
    url: http://host.docker.internal:4000
