openapi: 3.0.3

info:
  title: Medaware Catalyst
  description: The API Specification for Medaware
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local development environment

paths:
  /:
    get:
      operationId: catalystStatus
      summary: A status endpoint
      tags:
        - Status
      responses:
        200:
          description: Medaware Catalyst is up and running
          content:
            text/plain:
              schema:
                type: string

  /register:
    post:
      operationId: catalystRegister
      summary: Register a new Medaware user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/registrationRequest"
      responses:
        200:
          description: User successfully registered

  /login:
    post:
      operationId: catalystLogin
      summary: Provide authentication facilities for existing users
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/loginRequest"
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tokenResponse"

  /signout:
    post:
      operationId: catalystLogout
      summary: Log out a logged-in user
      tags:
        - Authentication
      responses:
        200:
          description: OK

components:
  schemas:
    catalystError:
      type: object
      required:
        - brief
        - message
        - status
      properties:
        brief:
          type: string
        message:
          type: string
        status:
          type: integer

    registrationRequest:
      type: object
      required:
        - userName
        - firstName
        - lastName
        - password
      properties:
        userName:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        password:
          type: string

    loginRequest:
      type: object
      required:
        - userName
        - password
      properties:
        userName:
          type: string
        password:
          type: string

    tokenResponse:
      type: object
      required:
        - token
      properties:
        token:
          type: string